# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20160725174150 on 2016-07-29 05:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crest', '0003_filedb_shared_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='filedb',
            name='file_signature',
            field=models.CharField(max_length=1000, null=True, verbose_name=b'file_signature'),
        ),
        migrations.AddField(
            model_name='filedb',
            name='public_key',
            field=models.CharField(max_length=1000, null=True, verbose_name=b'public_key'),
        ),
    ]
